[debug] [2025-03-06T06:40:01.220Z] ----------------------------------------------------------------------
[debug] [2025-03-06T06:40:01.223Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\notte\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2025-03-06T06:40:01.224Z] CLI Version:   13.32.0
[debug] [2025-03-06T06:40:01.224Z] Platform:      win32
[debug] [2025-03-06T06:40:01.224Z] Node Version:  v20.11.0
[debug] [2025-03-06T06:40:01.224Z] Time:          Thu Mar 06 2025 01:40:01 GMT-0500 (Eastern Standard Time)
[debug] [2025-03-06T06:40:01.224Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-03-06T06:40:01.230Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2025-03-06T06:40:01.488Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-03-06T06:40:01.489Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=568982634&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2025-03-06T06:40:04.344Z] Error: spawn cmd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-06T06:40:14.854Z] ----------------------------------------------------------------------
[debug] [2025-03-06T06:40:14.857Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\notte\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2025-03-06T06:40:14.857Z] CLI Version:   13.32.0
[debug] [2025-03-06T06:40:14.857Z] Platform:      win32
[debug] [2025-03-06T06:40:14.858Z] Node Version:  v20.11.0
[debug] [2025-03-06T06:40:14.858Z] Time:          Thu Mar 06 2025 01:40:14 GMT-0500 (Eastern Standard Time)
[debug] [2025-03-06T06:40:14.858Z] ----------------------------------------------------------------------
[debug] 
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=993980314&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2025-03-06T06:40:22.440Z] Error: spawn cmd ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[error] 
[error] Error: An unexpected error has occurred.
